version: '3.7'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    ports:
      - '3307:3307'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3307
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rooftop
      USER: 1000

  api:
    image: node:10.15
    hostname: api
    links:
      - mysql
    ports:
      - '3001:3001'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/packages/api
    command: yarn start

  website:
    image: node:10.15
    hostname: website
    links:
      - mysql
    ports:
      - '3000:3000'
      - '1235:1235'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/packages/website
    command: yarn start

  nginx:
    image: nginx
    hostname: nginx
    links:
      - api
      - website
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
