version: '3.7'
services:
  website:
    image: node:10.15
    hostname: website
    ports:
      - '3000:3000'
      - '1235:1235'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/
    command: yarn start

  nginx:
    image: nginx
    hostname: nginx
    links:
      - website
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
