version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/stage
    steps:
      - checkout

      - run:
          name: Install project's dependencies and configure
          command: |
            yarn install
            cp .env.example .env
      - run:
          name: Prettier rules
          command: yarn run prettier:check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
