version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/stage
    steps:
      - checkout
      - run:
          name: Install Yarn and project's dependencies
          command: |
            sudo apt install yarn
            yarn install
            cp .env.example .env
      - run:
          name: Tests Suites
          command: yarn run test
      - run:
          name: Prettier rules
          command: yarn run prettier:check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
