export const actionNames = {
  login: 'LOGIN',
  loggedIn: 'LOGGED_IN',
  loginFailed: 'LOGIN_FAILED',
  saveSession: 'SAVE_SESSION',
  deleteSession: 'DELETE_SESSION',
  loginError: 'LOGIN_ERROR',
  renewToken: 'RENEW_TOKEN',
  checkRoles: 'CHECK_ROLES',

  search: 'SEARCH_PRODUCTS',
  seeDetails: 'SEE_DETAILS',
  showDetails: 'SHOW_DETAILS',

  handleError: 'HANDLE_ERROR',

  loadFilters: 'LOAD_FILTERS',
  loadFiltersSuccesful: 'LOAD_FILTERS_SUCCESFUL',
  loadFiltersFail: 'LOAD_FILTERS_FAIL',

  showChangePasswordModal: 'SHOW_CHANGE_PASSWORD_MODAL',
  closeChangePasswordModal: 'CLOSE_CHANGE_PASSWORD_MODAL',
  changePassword: 'CHANGE_PASSWORD',
  passwordChangedSuccessfully: 'PASSWORD_CHANGED_SUCCESSFULLY',
  passwordChangedFail: 'PASSWORD_CHANGED_FAIL',

  loadingToggle: 'LOADING_TOGGLE',
  closeNotification: 'CLOSE_NOTIFICATION',
  showNotification: 'SHOW_NOTIFICATION',

  loadProducts: 'LOAD_PRODUCTS',
  loadProductsSuccessfully: 'LOAD_PRODUCTS_SUCCESSFULLY',
  loadProductsFail: 'LOAD_PRODUCTS_FAIL',

  loadProductsByFilterSuccessfully: 'LOAD_PRODUCTS_BY_FILTER_SUCCESSFULLY',
  loadProductsByFilterFail: 'LOAD_PRODUCTS_BY_FILTER_FAIL',

  nextSearchPage: 'NEXT_SEARCH_PAGE',
  previousSearchPage: 'PREVIOUS_SEARCH_PAGE',
  selectSearchPage: 'SELECT_SEARCH_PAGE',

  loadProductsWithDetailsSuccesful: 'LOAD_PRODUCT_WITH_DETAILS_SUCCESFUL',
  loadProductWithDetailsFail: 'LOAD_PRODUCT_WITH_DETAILS_FAIL',
  loadProductsHomeSuccessfully: 'LOAD_PRODUCTS_HOME_SUCCESSFULLY',
  loadProductsHomeFail: 'LOAD_PRODUCTS_HOME_FAIL',
  loadProductsForHome: 'LOAD_PRODUCTS_FOR_HOME',
  signUp: 'SIGN_UP',
  signUpSuccessfully: 'SIGN_UP_SUCCESSFULLY',
  signUpFail: 'SIGN_UP_FAIL',
  loadUserById: 'LOAD_USER_BY_ID',
  loadUserSuccessfully: 'LOAD_USER_SUCCESSFULLY',
  loadUserFail: 'LOAD_USER_FAIL',
  loadOrders: 'LOAD_ORDERS',
  loadOrdersFail: 'LOAD_ORDERS_FAIL',
  loadOrdersSuccessfully: 'LOAD_ORDERS_SUCCESSFULLY',
  updateCustomer: 'UPDATE_CUSTOMER',
  forgotPassword: 'FORGOT_PASSWORD',
  forgotPasswordFail: 'FORGOT_PASSWORD_FAIL',
  forgotPasswordSuccessfully: 'FORGOT_PASSWORD_SUCCESSFULLY',
  loadOrderByUuidSuccessfully: 'LOAD_ORDER_BY_UUID_SUCCESSFULLY',
  loadOrderByUuidFail: 'LOAD_ORDER_BY_UUID_FAIL',
  loadOrderByUuid: 'LOAD_ORDER_BY_UUID',
  addProductInCartSuccessfully: 'ADD_PRODUCT_IN_CART_SUCCESSFULLY',
  addProductInCartFail: 'ADD_PRODUCT_IN_CART_FAIL',
  removeProductInCartSuccessfully: 'REMOVE_PRODUCT_IN_CART_SUCCESSFULLY',
  removeProductInCartFail: 'REMOVE_PRODUCT_IN_CART_FAIL',
  mercadoPagoSelected: 'MERCADO_PAGO_SELECTED',
  addProductQuantityFromCart: 'ADD_PRODUCT_QUANTITY_FROM_CART',
  removeProductQuantityFromCart: 'REMOVE_PRODUCT_QUANTITY_FROM_CART',
  addProductQuantityFromCartSuccessfully: 'ADD_PRODUCT_QUANTITY_FROM_CART_SUCCESSFULLY',
  removeProductQuantityFromCartSuccessfully: 'REMOVE_PRODUCT_QUANTITY_FROM_CART_SUCCESSFULLY',
  saveProductsCart: 'SAVE_PRODUCTS_CART',
  addProductInShoppingCart: 'ADD_PRODUCT_IN_SHOPPING_CART',
  loadProductsFromShoppingCart: 'LOAD_PRODUCTS_FROM_SHOPPING_CART',
  loadProductsFromShoppingCartSuccessfully: 'LOAD_PRODUCTS_FROM_SHOPPING_CART_SUCCESSFULLY',
  loadProductsFromShoppingCartFail: 'LOAD_PRODUCTS_FROM_SHOPPING_CART_FAIL',
  removeProductInCart: 'REMOVE_PRODUCT_IN_CART',
};
