export const actionNames = {
  login: 'LOGIN',
  loggedIn: 'LOGGED_IN',
  loginFailed: 'LOGIN_FAILD',
  saveSession: 'SAVE_SESSION',
  deleteSession: 'DELETE_SESSION',
  createRooftopper: 'CREATE_ROOFTOPPER',
  listRooftoppers: 'LIST_ROOFTOPPERS',
  getRooftopperBySlug: 'LIST_ROOFTOPPER',
  updateRooftopper: 'UPDATE_ROOFTOPPER',
  changeStateRooftopper: 'CHANGE_STATE_ROOFTOPPER',
  loginError: 'LOGIN_ERROR',
  renewToken: 'RENEW_TOKEN',
  checkRoles: 'CHECK_ROLES',
  openDropDown: 'OPEN_DROPDOWN',
  closeDropDown: 'CLOSE_DROPDOWN',
};
